export const QuoteData = [
    { "id": 1, "tagId": 1, "author": "Albert Einstein", "text": "Life is like riding a bicycle. To keep your balance, you must keep moving." },
    { "id": 2, "tagId": 2, "author": "Oscar Wilde", "text": "Be yourself; everyone else is already taken." },
    { "id": 3, "tagId": 3, "author": "Maya Angelou", "text": "You will face many defeats in life, but never let yourself be defeated." },
    { "id": 4, "tagId": 4, "author": "Mark Twain", "text": "The two most important days in your life are the day you are born and the day you find out why." },
    { "id": 5, "tagId": 5, "author": "Winston Churchill", "text": "Success is not final, failure is not fatal: It is the courage to continue that counts." },
    { "id": 6, "tagId": 6, "author": "Mother Teresa", "text": "Not all of us can do great things. But we can do small things with great love." },
    { "id": 7, "tagId": 7, "author": "Socrates", "text": "The only true wisdom is in knowing you know nothing." },
    { "id": 8, "tagId": 1, "author": "Ralph Waldo Emerson", "text": "What lies behind us and what lies before us are tiny matters compared to what lies within us." },
    { "id": 9, "tagId": 2, "author": "Groucho Marx", "text": "I refuse to join any club that would have me as a member." },
    { "id": 10, "tagId": 3, "author": "Nelson Mandela", "text": "It always seems impossible until it’s done." },
    { "id": 11, "tagId": 4, "author": "Helen Keller", "text": "Life is either a daring adventure or nothing at all." },
    { "id": 12, "tagId": 5, "author": "Steve Jobs", "text": "Your work is going to fill a large part of your life, and the only way to be truly satisfied is to do what you believe is great work." },
    { "id": 13, "tagId": 6, "author": "Leo Tolstoy", "text": "All, everything that I understand, I understand only because I love." },
    { "id": 14, "tagId": 7, "author": "Confucius", "text": "Real knowledge is to know the extent of one’s ignorance." },
    { "id": 15, "tagId": 1, "author": "Mahatma Gandhi", "text": "Live as if you were to die tomorrow. Learn as if you were to live forever." },
    { "id": 16, "tagId": 2, "author": "George Carlin", "text": "The reason I talk to myself is because I’m the only one whose answers I accept." },
    { "id": 17, "tagId": 3, "author": "Vince Lombardi", "text": "It’s not whether you get knocked down, it’s whether you get up." },
    { "id": 18, "tagId": 4, "author": "John Lennon", "text": "Life is what happens when you’re busy making other plans." },
    { "id": 19, "tagId": 5, "author": "Michael Jordan", "text": "I’ve failed over and over and over again in my life and that is why I succeed." },
    { "id": 20, "tagId": 6, "author": "Victor Hugo", "text": "The greatest happiness of life is the conviction that we are loved." },
    { "id": 21, "tagId": 7, "author": "Aristotle", "text": "Knowing yourself is the beginning of all wisdom." },
    { "id": 22, "tagId": 1, "author": "Eleanor Roosevelt", "text": "The future belongs to those who believe in the beauty of their dreams." },
    { "id": 23, "tagId": 2, "author": "Bill Murray", "text": "The more relaxed you are, the better you are at everything." },
    { "id": 24, "tagId": 3, "author": "Thomas Edison", "text": "Our greatest weakness lies in giving up. The most certain way to succeed is always to try just one more time." },
    { "id": 25, "tagId": 4, "author": "Henry David Thoreau", "text": "Go confidently in the direction of your dreams! Live the life you’ve imagined." },
    { "id": 26, "tagId": 5, "author": "Napoleon Hill", "text": "The starting point of all achievement is desire." },
    { "id": 27, "tagId": 6, "author": "Pablo Neruda", "text": "Love is so short, forgetting is so long." },
    { "id": 28, "tagId": 7, "author": "Rumi", "text": "Yesterday I was clever, so I wanted to change the world. Today I am wise, so I am changing myself." },
    { "id": 29, "tagId": 1, "author": "Martin Luther King Jr.", "text": "The time is always right to do what is right." },
    { "id": 30, "tagId": 2, "author": "Robin Williams", "text": "You're only given a little spark of madness. You mustn't lose it." },
    { "id": 31, "tagId": 3, "author": "Lou Holtz", "text": "Ability is what you're capable of doing. Motivation determines what you do. Attitude determines how well you do it." },
    { "id": 32, "tagId": 4, "author": "Eleanor Roosevelt", "text": "Do what you feel in your heart to be right – for you’ll be criticized anyway." },
    { "id": 33, "tagId": 5, "author": "Tony Robbins", "text": "The path to success is to take massive, determined action." },
    { "id": 34, "tagId": 6, "author": "Jane Austen", "text": "There is no charm equal to tenderness of heart." },
    { "id": 35, "tagId": 7, "author": "Plato", "text": "Wise men speak because they have something to say; fools because they have to say something." },
    { "id": 36, "tagId": 1, "author": "Nelson Mandela", "text": "It always seems impossible until it’s done." },
    { "id": 37, "tagId": 2, "author": "Charlie Chaplin", "text": "A day without laughter is a day wasted." },
    { "id": 38, "tagId": 3, "author": "Helen Keller", "text": "Keep your face to the sun and you will never see the shadows." },
    { "id": 39, "tagId": 4, "author": "George Bernard Shaw", "text": "Life isn’t about finding yourself. Life is about creating yourself." },
    { "id": 40, "tagId": 5, "author": "Abraham Lincoln", "text": "The best way to predict your future is to create it." },
    { "id": 41, "tagId": 6, "author": "William Shakespeare", "text": "Love all, trust a few, do wrong to none." },
    { "id": 42, "tagId": 7, "author": "Albert Camus", "text": "In the depth of winter, I finally learned that within me there lay an invincible summer." },
    { "id": 43, "tagId": 1, "author": "Walt Disney", "text": "All our dreams can come true, if we have the courage to pursue them." },
    { "id": 44, "tagId": 2, "author": "Will Rogers", "text": "Everything is funny, as long as it's happening to somebody else." },
    { "id": 45, "tagId": 3, "author": "Babe Ruth", "text": "Every strike brings me closer to the next home run." },
    { "id": 46, "tagId": 4, "author": "Henry Ford", "text": "When everything seems to be going against you, remember that the airplane takes off against the wind, not with it." },
    { "id": 47, "tagId": 5, "author": "Vince Lombardi", "text": "Perfection is not attainable, but if we chase perfection we can catch excellence." },
    { "id": 48, "tagId": 6, "author": "Hermann Hesse", "text": "If I know what love is, it is because of you." },
    { "id": 49, "tagId": 7, "author": "Lao Tzu", "text": "Knowing others is intelligence; knowing yourself is true wisdom." },
    { "id": 50, "tagId": 1, "author": "Dr. Seuss", "text": "You have brains in your head. You have feet in your shoes. You can steer yourself any direction you choose." },
    { "id": 51, "tagId": 2, "author": "Stephen Colbert", "text": "You cannot truly call yourself peaceful unless you are capable of great violence." },
    { "id": 52, "tagId": 3, "author": "Muhammad Ali", "text": "I hated every minute of training, but I said, 'Don't quit. Suffer now and live the rest of your life as a champion.'" },
    { "id": 53, "tagId": 4, "author": "Albert Schweitzer", "text": "Success is not the key to happiness. Happiness is the key to success." },
    { "id": 54, "tagId": 5, "author": "Henry Ford", "text": "Whether you think you can or you think you can't, you're right." },
    { "id": 55, "tagId": 6, "author": "Edgar Allan Poe", "text": "We loved with a love that was more than love." },
    { "id": 56, "tagId": 7, "author": "Marcus Aurelius", "text": "The happiness of your life depends upon the quality of your thoughts." },
    { "id": 57, "tagId": 1, "author": "Mark Twain", "text": "The secret of getting ahead is getting started." },
    { "id": 58, "tagId": 2, "author": "Bill Hicks", "text": "It’s just a ride." },
    { "id": 59, "tagId": 3, "author": "Stephen Hawking", "text": "However difficult life may seem, there is always something you can do and succeed at." },
    { "id": 60, "tagId": 4, "author": "Bob Marley", "text": "Love the life you live. Live the life you love." },
    { "id": 61, "tagId": 5, "author": "Dale Carnegie", "text": "Develop success from failures. Discouragement and failure are two of the surest stepping stones to success." },
    { "id": 62, "tagId": 6, "author": "Emily Bronte", "text": "Whatever our souls are made of, his and mine are the same." },
    { "id": 63, "tagId": 7, "author": "Dalai Lama", "text": "When you talk, you are only repeating what you already know. But if you listen, you may learn something new." },
    { "id": 64, "tagId": 1, "author": "Bruce Lee", "text": "Knowing is not enough; we must apply. Willing is not enough; we must do." },
    { "id": 65, "tagId": 2, "author": "Woody Allen", "text": "Eighty percent of success is showing up." },
    { "id": 66, "tagId": 3, "author": "Samuel Beckett", "text": "Ever tried. Ever failed. No matter. Try again. Fail again. Fail better." },
    { "id": 67, "tagId": 4, "author": "Charles Dickens", "text": "It was the best of times, it was the worst of times." },
    { "id": 68, "tagId": 5, "author": "Vince Lombardi", "text": "Winners never quit and quitters never win." },
    { "id": 69, "tagId": 6, "author": "George Sand", "text": "There is only one happiness in this life, to love and be loved." },
    { "id": 70, "tagId": 7, "author": "Benjamin Franklin", "text": "An investment in knowledge pays the best interest." },
    { "id": 71, "tagId": 1, "author": "Confucius", "text": "It does not matter how slowly you go as long as you do not stop." },
    { "id": 72, "tagId": 2, "author": "Mitch Hedberg", "text": "I used to do drugs. I still do, but I used to, too." },
    { "id": 73, "tagId": 3, "author": "J.K. Rowling", "text": "It is our choices that show what we truly are, far more than our abilities." },
    { "id": 74, "tagId": 4, "author": "James Cameron", "text": "If you set your goals ridiculously high and it’s a failure, you will fail above everyone else’s success." },
    { "id": 75, "tagId": 5, "author": "Henry David Thoreau", "text": "Success usually comes to those who are too busy to be looking for it." }
  ]
  